version: 2
registries:
  public-npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org/
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "00:00"




