version: 2
registries:
  public-npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org/
    username: ''
    password: ''
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - public-npm-registry
    schedule:
      interval: weekly
      day: sunday
      time: "00:00"




